### PR TITLE
Link to sugar-high on README is 404.

### PR DESCRIPTION
**Pull request by sssionggg**
Fix it by removing the trailing .git extension which is unnecessary.

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Thanks :)

**Comment by sssionggg** [comment]
You are welcome. Off topic question: is https://github.com/kristianmandrup/troles usable?

**Comment by kristianmandrup** [comment]
Try the _simple_roles_ gem by @stanislaw for now or even _roles_active_record_ (more mature, _troles_ is a complete redesign of this gem). 

I've recently been working on _troles_ again in order to fix a few bugs caused by a refactoring we made, to extract the schema functionality to the _schemaker_ gem. The simple _troles_ strategies such as _bit_many_ should now be working.

**Comment by sssionggg** [comment]
thanks.

**Pull request merged**
